version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
    - 0.20.36
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.34
    - 14.14.35
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: karma-typescript
    versions:
    - 5.4.0
    - 5.5.0
  - dependency-name: semantic-release
    versions:
    - 17.4.1
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: core-js
    versions:
    - 3.9.1
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/examples/parcel"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/examples/webpack"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: start-server-and-test
    versions:
    - 1.12.0
  - dependency-name: webpack
    versions:
    - 5.19.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/examples/rollup"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
  registries:
  - npm-registry-registry-npmjs-org
