# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  headless:
    docker:
      - image: circleci/node:12-browsers
        environment:
          NODE_ENV: development
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run lint
      - run: npm run build
      - run: npm run coverage
  cbt:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm update -g cbt_tunnels
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test:browsers:legacy
      - run: npm run test:browsers:latest

workflows:
  version: 2
  push:
    jobs:
      - headless
  push_cbt:
    jobs:
      - cbt:
          filters:
            branches:
              only:
                - master
                - /.*-cbt/
  scheduled:
    jobs:
      - headless
      - cbt
    triggers:
      - schedule:
          cron: "8 8 * * 1"
          filters:
            branches:
              only:
                - master
